import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { CalendarIcon, Sparkles } from 'lucide-react';
import { format } from 'date-fns';
import { Calendar } from '@/components/ui/calendar';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import { cn } from '@/lib/utils';
import { users } from '@/data/mockData';
import { useAuth } from '@/context/AuthContext';
import { toast } from 'sonner';

interface AITaskGeneratorProps {
  teamId: string;
  onClose?: () => void;
}

export const AITaskGenerator = ({ teamId, onClose }: AITaskGeneratorProps) => {
  const { currentUser } = useAuth();
  const [prompt, setPrompt] = useState('');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [assigneeId, setAssigneeId] = useState('');
  const [priority, setPriority] = useState('medium');
  const [dueDate, setDueDate] = useState<Date>();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isTaskGenerated, setIsTaskGenerated] = useState(false);

  const teamMembers = users.filter(user => 
    user.teamId === teamId && user.role === 'employee'
  );

  // ✅ AI Task Generation using FastAPI
  const handleGenerateTask = async () => {
    if (!prompt.trim()) {
      toast.error('Please enter a task description first');
      return;
    }

    setIsGenerating(true);
    setIsTaskGenerated(false);

    try {
      const response = await fetch('http://localhost:8000/api/task-generator', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          team_id: teamId,
          context: prompt,
        }),
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.detail || 'AI generation failed');
      }

      const data = await response.json();
      setTitle(data.task_title);
      setDescription(data.task_description);
      setPriority('medium'); // Default fallback
      setIsTaskGenerated(true);
      toast.success('Task generated by AI');
    } catch (error: any) {
      toast.error(error.message || 'Error generating task');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCreateTask = () => {
    if (!title || !description || !assigneeId || !dueDate) {
      toast.error('Please fill in all required fields');
      return;
    }

    // Replace this with API to save task
    toast.success('Task created successfully');
    if (onClose) onClose();
  };

  return (
    <div className="space-y-4 py-2">
      {!isTaskGenerated ? (
        <>
          <div className="space-y-2">
            <Label htmlFor="prompt">Describe the task you'd like to create</Label>
            <Textarea
              id="prompt"
              placeholder="E.g. Create a dashboard mockup for our team's analytics"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={4}
            />
          </div>

          <Button 
            className="w-full"
            onClick={handleGenerateTask}
            disabled={isGenerating}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            {isGenerating ? 'Generating...' : 'Generate Task with AI'}
          </Button>
        </>
      ) : (
        <>
          <div className="border-l-4 border-bloom-purple bg-bloom-purple/5 p-3 mb-4">
            <div className="flex items-center gap-2 text-sm text-bloom-purple">
              <Sparkles className="h-4 w-4" />
              <span className="font-medium">AI-Generated Task</span>
            </div>
          </div>

          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="title">Task Title</Label>
              <Input
                id="title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">Task Description</Label>
              <Textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={4}
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="assignee">Assign To</Label>
                <Select value={assigneeId} onValueChange={setAssigneeId}>
                  <SelectTrigger id="assignee">
                    <SelectValue placeholder="Select team member" />
                  </SelectTrigger>
                  <SelectContent>
                    {teamMembers.map(member => (
                      <SelectItem key={member.id} value={member.id}>
                        {member.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="priority">Priority</Label>
                <Select value={priority} onValueChange={setPriority}>
                  <SelectTrigger id="priority">
                    <SelectValue placeholder="Select priority" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="low">Low</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="dueDate">Due Date</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    id="dueDate"
                    variant="outline"
                    className={cn(
                      "w-full justify-start text-left font-normal",
                      !dueDate && "text-muted-foreground"
                    )}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {dueDate ? format(dueDate, "PPP") : "Select due date"}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0">
                  <Calendar
                    mode="single"
                    selected={dueDate}
                    onSelect={setDueDate}
                    initialFocus
                    className="pointer-events-auto"
                  />
                </PopoverContent>
              </Popover>
            </div>
          </div>

          <div className="flex justify-end space-x-2 pt-4">
            <Button variant="outline" onClick={() => setIsTaskGenerated(false)}>
              Back
            </Button>
            <Button onClick={handleCreateTask}>
              Create Task
            </Button>
          </div>
        </>
      )}
    </div>
  );
};
